/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2024 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "lwip.h"
#include "rng.h"
#include "spi.h"
#include "usart.h"
#include "usb_otg.h"
#include "gpio.h"
#include "tcp_priv.h"
#include "udp.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */



/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */
/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */


/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */
#ifdef __GNUC__
#define PUTCHAR_PROTOTYPE int __io_putchar(int ch)
#else
#define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
#endif

PUTCHAR_PROTOTYPE
{
    HAL_UART_Transmit(&huart3, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */
#include <wolfssl/ssl.h>
#include <wolfssl/wolfcrypt/settings.h>
#include <lwip/tcp.h>
#include <lwip/dns.h>

// Network interface (generated by STM32CubeMX)
extern struct netif gnetif;

// DNS and TLS state
static uint8_t dns_found_called = 0;
static ip_addr_t resolved_ip;
static struct tcp_pcb *tls_pcb = NULL;
static WOLFSSL *ssl = NULL;
static uint8_t tls_connected = 0;
static uint8_t request_sent = 0;

// Buffer for received data
static char recv_buffer[512];
static int recv_buffer_len = 0;

// DNS callback function
static void dns_found(const char *name, const ip_addr_t *ipaddr, void *callback_arg) {
    dns_found_called = 1;
    if (ipaddr != NULL) {
        resolved_ip = *ipaddr;
        printf("Resolved %s to %s\n", name, ipaddr_ntoa(ipaddr));
    } else {
        printf("Failed to resolve %s\n", name);
    }
}

// wolfSSL I/O callbacks for lwIP raw API
static int wolfssl_recv(WOLFSSL *ssl, char *buf, int sz, void *ctx) {
    struct tcp_pcb *pcb = (struct tcp_pcb *)ctx;
    if (recv_buffer_len <= 0) {
        return WOLFSSL_CBIO_ERR_WANT_READ; // No data available
    }

    // Copy data to wolfSSL's buffer
    int copy_len = (recv_buffer_len < sz) ? recv_buffer_len : sz;
    memcpy(buf, recv_buffer, copy_len);

    // Update buffer (shift remaining data)
    if (copy_len < recv_buffer_len) {
        memmove(recv_buffer, recv_buffer + copy_len, recv_buffer_len - copy_len);
    }
    recv_buffer_len -= copy_len;

    // Acknowledge data to lwIP
    tcp_recved(pcb, copy_len);

    return copy_len;
}

static int wolfssl_send(WOLFSSL *ssl, char *buf, int sz, void *ctx) {
    struct tcp_pcb *pcb = (struct tcp_pcb *)ctx;
    err_t ret = tcp_write(pcb, buf, sz, TCP_WRITE_FLAG_COPY);
    if (ret != ERR_OK) {
        return WOLFSSL_CBIO_ERR_GENERAL;
    }
    tcp_output(pcb);
    return sz;
}

// TCP callbacks
static err_t wolf_tcp_sent(void *arg, struct tcp_pcb *tpcb, u16_t len) {
    return ERR_OK;
}

static err_t wolf_tcp_recv(void *arg, struct tcp_pcb *tpcb, struct pbuf *p, err_t err) {
    if (p == NULL) {
        // Connection closed
        printf("TCP connection closed\n");
        if (ssl) {
            wolfSSL_free(ssl);
            ssl = NULL;
        }
        tcp_close(tpcb);
        tls_pcb = NULL;
        return ERR_OK;
    }
    if (err != ERR_OK) {
        printf("TCP receive error: %d\n", err);
        pbuf_free(p);
        return err;
    }

    // Copy received data to buffer
    if (recv_buffer_len + p->tot_len > sizeof(recv_buffer)) {
        printf("Receive buffer overflow\n");
        pbuf_free(p);
        return ERR_MEM;
    }
    pbuf_copy_partial(p, recv_buffer + recv_buffer_len, p->tot_len, 0);
    recv_buffer_len += p->tot_len;

    // Acknowledge data
    tcp_recved(tpcb, p->tot_len);
    pbuf_free(p);

    // Process data with wolfSSL if request was sent
    if (request_sent && ssl) {
        int ret = wolfSSL_read(ssl, recv_buffer, recv_buffer_len);
        if (ret > 0) {
            recv_buffer[ret] = '\0';
            printf("Received %d bytes:\n%s\n", ret, recv_buffer);
            // Shift remaining data
            if (ret < recv_buffer_len) {
                memmove(recv_buffer, recv_buffer + ret, recv_buffer_len - ret);
            }
            recv_buffer_len -= ret;
        } else {
            int error = wolfSSL_get_error(ssl, ret);
            if (error != WOLFSSL_ERROR_WANT_READ) {
                printf("wolfSSL read failed: %d\n", error);
            }
        }
    }

    return ERR_OK;
}

static err_t tcp_connected(void *arg, struct tcp_pcb *tpcb, err_t err) {

    if (err != ERR_OK) {
        printf("TCP connection failed: %d\n", err);
        tcp_close(tpcb);
        return err;
    }

    printf("Initialize wolfSSL \n");
    WOLFSSL_CTX * ctx = wolfSSL_CTX_new(wolfTLSv1_3_client_method());
    if (ctx == NULL) {
        printf("Failed to create wolfSSL context\n");
        tcp_close(tpcb);
        return ERR_MEM;
    }

    //  wolfSSL_SetLoggingCb();
    wolfSSL_Debugging_ON();

    printf("Disable certificate verification (INSECURE, for testing only) \n");
    wolfSSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, NULL);

    printf("Create wolfSSL session \n");
    ssl = wolfSSL_new(ctx);
    if (ssl == NULL) {
        printf("Failed to create wolfSSL session\n");
        wolfSSL_CTX_free(ctx);
        tcp_close(tpcb);
        return ERR_MEM;
    }

    printf("Set I/O callbacks \n");
    wolfSSL_SetIOReadCtx(ssl, tpcb);
    wolfSSL_SetIOWriteCtx(ssl, tpcb);
    wolfSSL_SetIORecv(ctx, wolfssl_recv);
    wolfSSL_SetIOSend(ctx, wolfssl_send);

    printf("Set SNI \n");
    if (wolfSSL_UseSNI(ssl, WOLFSSL_SNI_HOST_NAME, "google.com", strlen("google.com")) != WOLFSSL_SUCCESS) {
        printf("Failed to set SNI\n");
        wolfSSL_free(ssl);
        wolfSSL_CTX_free(ctx);
        tcp_close(tpcb);
        return ERR_MEM;
    }

    printf("Perform TLS handshake \n");
    if (wolfSSL_connect(ssl) != SSL_SUCCESS) {
        printf("TLS handshake failed: %d\n", wolfSSL_get_error(ssl, 0));
        wolfSSL_free(ssl);
        wolfSSL_CTX_free(ctx);
        tcp_close(tpcb);
        return ERR_CONN;
    }

    tls_connected = 1;

    printf("Send HTTPS GET request \n");
    const char *request = "GET / HTTP/1.1\r\nHost: google.com\r\nConnection: close\r\n\r\n";
    int bytes_sent = wolfSSL_write(ssl, request, strlen(request));
    if (bytes_sent <= 0) {
        printf("Failed to send HTTPS request: %d\n", wolfSSL_get_error(ssl, bytes_sent));
    } else {
        printf("Sent HTTPS GET request (%d bytes)\n", bytes_sent);
        request_sent = 1;
    }

    wolfSSL_CTX_free(ctx); // Free context after handshake


    return ERR_OK;
}


/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */
   uint32_t last_time = HAL_GetTick();
  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */
  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */
  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART3_UART_Init();
  MX_USB_OTG_FS_PCD_Init();
  MX_SPI1_Init();
  MX_LWIP_Init();
  MX_RNG_Init();

  /* USER CODE BEGIN 2 */
  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
    ip_addr_t dns_server;
    IP4_ADDR(&dns_server, 8, 8, 8, 8);  // Use Google’s DNS as an example
    dns_setserver(0, &dns_server);

    printf("------------------------------------------------------------------------- \n");
    err_t error = dns_gethostbyname("google.com", &resolved_ip, dns_found, NULL);
    if (error == ERR_OK)
    {
        printf("DNS test result: %d \n", error);
    } else if (error == ERR_INPROGRESS)
    {
            printf("DNS resolution in progress... \n", error);
    } else
    {
            printf("DNS resolution error: %d \n", error);
    }

    printf("Wait for DNS resolution with timeout \n");
    uint32_t start_time = HAL_GetTick();
    while (!dns_found_called && (HAL_GetTick() - start_time < 5000)) {
        MX_LWIP_Process(); // Handle lwIP tasks
    }
    if (!dns_found_called) {
        printf("DNS resolution timed out\n");
        while (1); // Halt for debugging
    }

    printf("Create TCP PCB \n");
    tls_pcb = tcp_new();
    if (tls_pcb == NULL) {
        printf("Failed to create TCP PCB\n");
        while (1);
    }

    printf("Set TCP callbacks \n");
    tcp_arg(tls_pcb, NULL);
    tcp_sent(tls_pcb, wolf_tcp_sent);
    tcp_recv(tls_pcb, wolf_tcp_recv);

    printf("Connect to server \n");
    printf("Destination IP address:  %s\n", ipaddr_ntoa(&resolved_ip));
    err_t err = tcp_connect(tls_pcb, &resolved_ip, 443, tcp_connected);
    printf("error: %d \n", err);
    if (err != ERR_OK) {
        printf("TCP connect failed: %d\n", err);
        tcp_close(tls_pcb);
        while (1);
    }


  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
     MX_LWIP_Process();
    /* USER CODE END WHILE */
    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_BYPASS;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 4;
  RCC_OscInitStruct.PLL.PLLN = 168;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 7;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
